// Code generated by protoc-gen-gin v0.1.0. DO NOT EDIT.
// source: user/v1/user.proto

package userv1

import (
	errors "errors"
	ginruntime "github.com/Linuxea/protoc-gen-gin/ginruntime"
	gin "github.com/gin-gonic/gin"
	io "io"
	http "net/http"
)

// UserServiceGetUserHandler adapts the unary RPC user.v1.UserService.GetUser to a gin route.
//
// @Summary      GetUser
// @Description  GetUser 根据 ID 获取用户。
// @Tags         UserService
// @ID           user.v1.UserService.GetUser
// @Accept       json
// @Produce      json
// @Param        request body GetUserRequest true "GetUser request body"
// @Success      200 {object} GetUserResponse
// @Failure      400 {object} ginruntime.Error
// @Failure      500 {object} ginruntime.Error
// @Router       /user.v1.UserService/GetUser [post]
func UserServiceGetUserHandler(cli UserServiceClient) gin.HandlerFunc {
	return func(c *gin.Context) {
		var req GetUserRequest
		if err := c.ShouldBindJSON(&req); err != nil && !errors.Is(err, io.EOF) {
			c.JSON(http.StatusBadRequest, ginruntime.Error{Code: 3, Message: "invalid request: " + err.Error()}) // 3 = codes.InvalidArgument
			return
		}
		resp, err := cli.GetUser(c.Request.Context(), &req)
		if err != nil {
			httpStatus, code, message := ginruntime.HTTPStatus(err)
			c.JSON(httpStatus, ginruntime.Error{Code: code, Message: message})
			return
		}
		c.JSON(http.StatusOK, resp)
	}
}

// UserServiceUpdateUserHandler adapts the unary RPC user.v1.UserService.UpdateUser to a gin route.
//
// @Summary      UpdateUser
// @Description  UpdateUser 更新用户信息。
// @Description  id 为必填。
// @Tags         UserService
// @ID           user.v1.UserService.UpdateUser
// @Accept       json
// @Produce      json
// @Param        request body UpdateUserRequest true "UpdateUser request body"
// @Success      200 {object} UpdateUserResponse
// @Failure      400 {object} ginruntime.Error
// @Failure      500 {object} ginruntime.Error
// @Router       /user.v1.UserService/UpdateUser [post]
func UserServiceUpdateUserHandler(cli UserServiceClient) gin.HandlerFunc {
	return func(c *gin.Context) {
		var req UpdateUserRequest
		if err := c.ShouldBindJSON(&req); err != nil && !errors.Is(err, io.EOF) {
			c.JSON(http.StatusBadRequest, ginruntime.Error{Code: 3, Message: "invalid request: " + err.Error()}) // 3 = codes.InvalidArgument
			return
		}
		resp, err := cli.UpdateUser(c.Request.Context(), &req)
		if err != nil {
			httpStatus, code, message := ginruntime.HTTPStatus(err)
			c.JSON(httpStatus, ginruntime.Error{Code: code, Message: message})
			return
		}
		c.JSON(http.StatusOK, resp)
	}
}

// RegisterUserServiceGin registers every unary method of user.v1.UserService as a gin POST route.
// Route paths have the form /user.v1.UserService/<Method>.
// Streaming methods are not registered.
func RegisterUserServiceGin(r gin.IRoutes, cli UserServiceClient) {
	r.POST("/user.v1.UserService/GetUser", UserServiceGetUserHandler(cli))
	r.POST("/user.v1.UserService/UpdateUser", UserServiceUpdateUserHandler(cli))
	// WARNING: streaming method WatchUsers is not registered (only unary methods are supported).
}

// NotificationServiceSendHandler adapts the unary RPC user.v1.NotificationService.Send to a gin route.
//
// @Summary      Send
// @Description  Send 给指定用户发送通知。
// @Tags         NotificationService
// @ID           user.v1.NotificationService.Send
// @Accept       json
// @Produce      json
// @Param        request body SendRequest true "Send request body"
// @Success      200 {object} SendResponse
// @Failure      400 {object} ginruntime.Error
// @Failure      500 {object} ginruntime.Error
// @Router       /user.v1.NotificationService/Send [post]
func NotificationServiceSendHandler(cli NotificationServiceClient) gin.HandlerFunc {
	return func(c *gin.Context) {
		var req SendRequest
		if err := c.ShouldBindJSON(&req); err != nil && !errors.Is(err, io.EOF) {
			c.JSON(http.StatusBadRequest, ginruntime.Error{Code: 3, Message: "invalid request: " + err.Error()}) // 3 = codes.InvalidArgument
			return
		}
		resp, err := cli.Send(c.Request.Context(), &req)
		if err != nil {
			httpStatus, code, message := ginruntime.HTTPStatus(err)
			c.JSON(httpStatus, ginruntime.Error{Code: code, Message: message})
			return
		}
		c.JSON(http.StatusOK, resp)
	}
}

// RegisterNotificationServiceGin registers every unary method of user.v1.NotificationService as a gin POST route.
// Route paths have the form /user.v1.NotificationService/<Method>.
// Streaming methods are not registered.
func RegisterNotificationServiceGin(r gin.IRoutes, cli NotificationServiceClient) {
	r.POST("/user.v1.NotificationService/Send", NotificationServiceSendHandler(cli))
}
