// Package internal implements the code generation logic of protoc-gen-gin.
package internal

import (
	"fmt"
	"os"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// Version is the plugin version reported in generated file headers.
const Version = "0.1.0"

var (
	ginImport     = protogen.GoImportPath("github.com/gin-gonic/gin")
	runtimeImport = protogen.GoImportPath("github.com/Linuxea/protoc-gen-gin/ginruntime")
	httpImport    = protogen.GoImportPath("net/http")
	errorsImport  = protogen.GoImportPath("errors")
	ioImport      = protogen.GoImportPath("io")
)

// GenerateFile generates a "<prefix>.gin.pb.go" file for every proto file that
// declares at least one unary RPC method. Files without services, or whose
// methods are all streaming, are skipped (with a warning on stderr for the
// latter).
func GenerateFile(gen *protogen.Plugin, f *protogen.File) *protogen.GeneratedFile {
	if len(f.Services) == 0 {
		return nil
	}
	unary := 0
	streaming := 0
	for _, s := range f.Services {
		for _, m := range s.Methods {
			if isUnary(m) {
				unary++
			} else {
				streaming++
			}
		}
	}
	if unary == 0 {
		fmt.Fprintf(os.Stderr, "[protoc-gen-gin] %s: all methods are streaming, file skipped\n", f.Desc.Path())
		return nil
	}
	if streaming > 0 {
		fmt.Fprintf(os.Stderr, "[protoc-gen-gin] %s: %d streaming method(s) skipped\n", f.Desc.Path(), streaming)
	}

	g := gen.NewGeneratedFile(f.GeneratedFilenamePrefix+".gin.pb.go", f.GoImportPath)
	g.P("// Code generated by protoc-gen-gin v" + Version + ". DO NOT EDIT.")
	g.P("// source: " + f.Desc.Path())
	g.P()
	g.P("package " + string(f.GoPackageName))
	g.P()

	for _, s := range f.Services {
		generateService(g, f, s)
		g.P()
	}
	return g
}

func isUnary(m *protogen.Method) bool {
	return !m.Desc.IsStreamingClient() && !m.Desc.IsStreamingServer()
}

func clientIdent(g *protogen.GeneratedFile, f *protogen.File, s *protogen.Service) string {
	return g.QualifiedGoIdent(protogen.GoIdent{
		GoName:       s.GoName + "Client",
		GoImportPath: f.GoImportPath,
	})
}

func generateService(g *protogen.GeneratedFile, f *protogen.File, s *protogen.Service) {
	for _, m := range s.Methods {
		if isUnary(m) {
			generateHandler(g, f, s, m)
			g.P()
		}
	}

	client := clientIdent(g, f, s)
	routes := g.QualifiedGoIdent(ginImport.Ident("IRoutes"))
	g.P("// Register" + s.GoName + "Gin registers every unary method of " +
		string(s.Desc.FullName()) + " as a gin POST route.")
	g.P("// Route paths have the form /" + string(s.Desc.FullName()) + "/<Method>.")
	g.P("// Streaming methods are not registered.")
	g.P("func Register" + s.GoName + "Gin(r " + routes + ", cli " + client + ") {")
	for _, m := range s.Methods {
		if !isUnary(m) {
			g.P("\t// WARNING: streaming method " + string(m.Desc.Name()) +
				" is not registered (only unary methods are supported).")
			continue
		}
		g.P("\tr.POST(\"/" + string(s.Desc.FullName()) + "/" + string(m.Desc.Name()) + "\", " +
			s.GoName + m.GoName + "Handler(cli))")
	}
	g.P("}")
}

// generateHandler emits one exported handler function per unary method, with a
// swaggo/swag annotation block so `swag init` can produce API docs.
func generateHandler(g *protogen.GeneratedFile, f *protogen.File, s *protogen.Service, m *protogen.Method) {
	name := s.GoName + m.GoName + "Handler"
	client := clientIdent(g, f, s)
	reqType := g.QualifiedGoIdent(m.Input.GoIdent)
	respType := g.QualifiedGoIdent(m.Output.GoIdent)
	route := "/" + string(s.Desc.FullName()) + "/" + string(m.Desc.Name())

	handlerFunc := g.QualifiedGoIdent(ginImport.Ident("HandlerFunc"))
	ctxType := g.QualifiedGoIdent(ginImport.Ident("Context"))
	badRequest := g.QualifiedGoIdent(httpImport.Ident("StatusBadRequest"))
	okStatus := g.QualifiedGoIdent(httpImport.Ident("StatusOK"))
	errorsIs := g.QualifiedGoIdent(errorsImport.Ident("Is"))
	ioEOF := g.QualifiedGoIdent(ioImport.Ident("EOF"))
	runtimeErr := g.QualifiedGoIdent(runtimeImport.Ident("Error"))
	runtimeHTTPStatus := g.QualifiedGoIdent(runtimeImport.Ident("HTTPStatus"))

	g.P("// " + name + " adapts the unary RPC " + string(m.Desc.FullName()) + " to a gin route.")
	g.P("//")
	g.P("// @Summary      " + m.GoName)
	for _, line := range commentLines(m.Comments) {
		g.P("// @Description  " + line)
	}
	g.P("// @Tags         " + s.GoName)
	g.P("// @ID           " + string(m.Desc.FullName()))
	g.P("// @Accept       json")
	g.P("// @Produce      json")
	g.P("// @Param        request body " + reqType + " true \"" + m.GoName + " request body\"")
	g.P("// @Success      200 {object} " + respType)
	g.P("// @Failure      400 {object} " + runtimeErr)
	g.P("// @Failure      500 {object} " + runtimeErr)
	g.P("// @Router       " + route + " [post]")
	g.P("func " + name + "(cli " + client + ") " + handlerFunc + " {")
	g.P("\treturn func(c *" + ctxType + ") {")
	g.P("\t\tvar req " + reqType)
	g.P("\t\tif err := c.ShouldBindJSON(&req); err != nil && !" + errorsIs + "(err, " + ioEOF + ") {")
	g.P("\t\t\tc.JSON(" + badRequest + ", " + runtimeErr + "{Code: 3, Message: \"invalid request: \" + err.Error()}) // 3 = codes.InvalidArgument")
	g.P("\t\t\treturn")
	g.P("\t\t}")
	g.P("\t\tresp, err := cli." + m.GoName + "(c.Request.Context(), &req)")
	g.P("\t\tif err != nil {")
	g.P("\t\t\thttpStatus, code, message := " + runtimeHTTPStatus + "(err)")
	g.P("\t\t\tc.JSON(httpStatus, " + runtimeErr + "{Code: code, Message: message})")
	g.P("\t\t\treturn")
	g.P("\t\t}")
	g.P("\t\tc.JSON(" + okStatus + ", resp)")
	g.P("\t}")
	g.P("}")
}

// commentLines extracts the cleaned leading comment lines of a method, used as
// the swag @Description content.
func commentLines(cs protogen.CommentSet) []string {
	if cs.Leading == "" {
		return nil
	}
	var lines []string
	for _, line := range strings.Split(string(cs.Leading), "\n") {
		line = strings.TrimSpace(strings.TrimSuffix(line, "\r"))
		if line != "" {
			lines = append(lines, line)
		}
	}
	return lines
}
